# -*- coding: utf-8 -*-
"""Root Segmenter Final Masters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOEjqxvoz2DjffN8xRvOk6jvV0Q5b2CO
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from PIL import Image
import numpy as np
import os
import skimage.measure

LABEL_COLORS = [(0,0,0), (255,0,0)]

imageFile = np.load("drive/MyDrive/Roots/RootImages.npz")
trainLabelFile = np.load("drive/MyDrive/Roots/TrainLabels.npz")
valLabelFile = np.load("drive/MyDrive/Roots/ValLabels.npz")

def pairImages2Labels(imageFile, labelFile, scale=1.0):
    images = []
    labels = []

    for k in labelFile.files:
        img = imageFile[k]
        img = img[..., :-1]
        label = labelFile[k]

        if scale != 1.0:
            s = int(1 // scale)
            img = skimage.measure.block_reduce(img, (s, s, 1), np.max)
            label = skimage.measure.block_reduce(label, (s, s, 1), np.max)

        images.append(img)
        labels.append(label)

    return np.array(images), np.array(labels)

#CNNs are not scale invariant, so inference must use the same scale as training.
#The distributed network was trained at .5, which makes its input 800x832 for the
#1664x1600 main dataset.  Controller.runInitial currently feeds full resolution images.
SCALE = .5

trainData, trainLabels = pairImages2Labels(imageFile, trainLabelFile, scale=SCALE)
valData, valLabels = pairImages2Labels(imageFile, valLabelFile, scale=SCALE)

#del name2Image
#del name2TrainLabel
#del name2ValLabel

print(trainData.shape, trainData.dtype)
print(trainLabels.shape, trainLabels.dtype)
print(valData.shape, valData.dtype)
print(valLabels.shape, valLabels.dtype)

def makeModel(input, filters, transitions, blockDepth, regularizer=None):
    x = layers.Conv2D(filters, (3,3), padding='same', activation='relu', activity_regularizer=regularizer)(input)
    x = layers.BatchNormalization()(x)

    concatinations = []
    for i in range(transitions):
        x = connectedConvBlock(x, filters, blockDepth, regularizer=regularizer)
        concatinations.append(x)
        x = layers.MaxPool2D()(x)
        x = layers.BatchNormalization()(x)
        filters *= 2

    #This is the most spatially compressed part of the network, so a convolution here sees
    #more of the image than anywhere else.  The 7x7 kernels take advantage of that to pull in
    #global information.  The trained network was produced with these kernels.
    x = layers.Conv2D(filters, (7,7), padding='same', activation='relu', activity_regularizer=regularizer)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Conv2D(filters, (7,7), padding='same', activation='relu', activity_regularizer=regularizer)(x)
    x = layers.BatchNormalization()(x)

    for i in range(transitions):
        filters //= 2
        x = layers.Conv2DTranspose(filters, (4,4), strides=(2,2), padding='same', activation='relu', activity_regularizer=regularizer)(x)
        c = concatinations.pop()
        x = layers.Concatenate()([x, c])
        x = connectedConvBlock(x, filters, blockDepth, regularizer=regularizer)

    x = layers.Conv2D(filters, (3,3), padding='same', activation='relu', activity_regularizer=regularizer)(x)
    beforeOutput = layers.BatchNormalization()(x)

    x = layers.Conv2D(1, (1,1), padding='same', activity_regularizer=regularizer)(beforeOutput)
    output = layers.Activation('sigmoid', dtype='float32')(x)

    return input, output, beforeOutput


def connectedConvBlock(input, filters, depth, dropout=.25, regularizer=None):
    c = input
    convelutions = []
    for _ in range(depth):
        x = layers.Conv2D(filters, (3,3), padding = 'same', activation = 'relu', activity_regularizer=regularizer)(c)
        x = layers.BatchNormalization()(x)
        x = layerDropout(x, dropout)
        convelutions.append(x)
        c = layers.Concatenate()([c, x])

    x = layers.Concatenate()(convelutions)
    return x


#Randomly applies dropout to the entire layer at once, or nothing
def layerDropout(input, prob):
    return layers.Dropout(prob, noise_shape = (None, 1, 1, 1))(input)

def resetBackend():
    tf.keras.backend.clear_session()
    tf.keras.backend.set_floatx('float32')

from tensorflow.keras import layers
from tensorflow.keras import Model



resetBackend()


input = layers.Input(trainData[0].shape)

x, y, z = makeModel(input, 8, 5, 3)

model = Model(input, y)

#l = tf.keras.regularizers.L1(l1=.01)
#model.add_loss(l(y))

model.summary()

import tensorflow.keras.backend as K
from tensorflow.keras.losses import Loss


def dice(y_true, y_pred, smooth=1e-7):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersect = K.sum(y_true_f * y_pred_f, axis=-1)
    denom = K.sum(y_true_f + y_pred_f, axis=-1)
    return 1 - K.mean((2 * intersect / (denom + smooth)))

#Set up train
from tensorflow.keras.metrics import Mean, MeanAbsolutePercentageError, BinaryAccuracy
from tensorflow.keras.losses import CategoricalCrossentropy, BinaryCrossentropy

model.compile(optimizer='adam',
              loss=[dice],
              #loss=[BinaryCrossentropy()]
              metrics=[BinaryAccuracy()],
              )

import matplotlib.pyplot as plt


def show(image, size=10, colors=None):
    if isinstance(image, np.ndarray) or isinstance(image, tf.Tensor):
        if image.shape[-1] == 1:
            colors = [1]
        else:
            image = np.squeeze(image)
        if len(image.shape) <= 3:
            image = [image]
    showImages(image, size, colors)


#shrinks to fit window if not enough room
def showImages(images, size=10, colors=None):
    fig, axes = plt.subplots(1, len(images), figsize=(size * len(images), size))
    if len(images) > 1:
        axes = axes.flatten()
    else:
        axes = [axes]
    for img, ax in zip(images, axes):
        if img.dtype == np.float16:
            img = img.astype(np.float32)
        if colors is not None:
            img = label2img(img, colors)
        if img.dtype == int:
            img = img.astype(np.float)
            img /= 255
        ax.imshow(img)
        ax.axis('off')
    plt.tight_layout()
    plt.show()


def label2img(label, colors):
    img = np.zeros((*label.shape[:-1], 3))
    for i, c in enumerate(colors):
        x = np.tile(c, (*label.shape[:-1], 1))
        img += x * label[:,:,i:i+1]
    return img

#Shows correct mask, predicted mask, and overlap + false positives
class DisplayImageSegmentation(tf.keras.callbacks.Callback):
    def __init__(self, images, labels, inputShowRate=100, predictionShowRate=5, imageColors=None, labelColors=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.images = images
        self.labels = labels
        self.inputShowRate = inputShowRate
        self.predictionShowRate = predictionShowRate
        self.imageColors = imageColors
        self.labelColors = labelColors

    def on_epoch_end(self, epoch, logs=None):
        if self.inputShowRate is not None:
            if epoch % self.inputShowRate == 0:
                show(self.images, colors=self.imageColors)
                show(self.labels, colors=self.labelColors)

        if self.predictionShowRate is not None:
            if epoch % self.predictionShowRate == 0:
                pred = model(self.images)
                pred = pred.numpy()
                show(pred, colors=self.labelColors)

from tensorflow.keras.callbacks import ModelCheckpoint


checkpoint_filepath = 'drive/MyDrive/Roots/Models/{val_loss:.4f}.hdf5'
model_checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=False,
    monitor='val_loss',  # Or 'val_accuracy' if monitoring accuracy
    mode='min',  # Use 'min' for loss and 'max' for accuracy
    save_best_only=True)

callbacks_list = [DisplayImageSegmentation(valData[6:7], valLabels[6:7], labelColors=LABEL_COLORS), model_checkpoint_callback]

model.fit(trainData, trainLabels, validation_data=(valData, valLabels), epochs=10001, batch_size=4,
          callbacks = callbacks_list,)

model = tf.keras.models.load_model("drive/MyDrive/Roots5/Models/0.0558.hdf5", custom_objects={"dice": dice})
model.save("drive/MyDrive/Roots5/network6")

model = tf.keras.models.load_model("drive/MyDrive/Roots/Models2/0.0539.hdf5", custom_objects={"dice": dice})

#weights = model.get_weights()
#print(type(weights))
#np.savez_compressed("drive/MyDrive/Roots/network.npz", weights)

weights = model.get_weights()
print(type(model))
#weights = np.array(weights)
print(type(weights), len(weights))
np.savez("drive/MyDrive/Roots/network.npz", weights)